apiVersion: apps/v1
kind: Deployment
metadata:
  name: main-deployment
spec:
  selector:
    matchLabels:
      app: flask
  replicas: 2
  revisionHistoryLimit: 0
  progressDeadlineSeconds: 30
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 2
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
      - name: flask
        image: 23emre/flask-docker:latest
        ports:
        - containerPort: 5000
